import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { EventCard } from '../components/Events'
import { Button, BulletList, LeftDashedBorder } from '../components/Utils'

import styles from './index.module.scss'

const whoWeAreTexts = [
    <React.Fragment key={0}>A <span className='redUnderline'>Diverse</span> group of young professionals</React.Fragment>,
    <React.Fragment key={1}>COMMITTED TO <span className='redUnderline'>GIVING BACK</span> TO OUR COMMUNITY</React.Fragment>,
    <React.Fragment key={2}>CURRENT AND FUTURE <span className='redUnderline'>VISIONARY LEADERS</span></React.Fragment>,
    <React.Fragment key={3}>GLOBAL <span className='redUnderline'>ADVENTURERS</span> HELPING OUT ABROAD</React.Fragment>,
    <React.Fragment key={4}>DEDICATED TO <span className='redUnderline'>LOCAL</span> PHILANTHROPIC INITIATIVES</React.Fragment>,
]

const volunteerOpportunities = [
    { logo: '/logos/civic-engagement.svg', title: 'Civic Engagement', description: 'Sounding off on local issues and taking a closer look at our community' },
    { logo: '/logos/interactive.svg', title: 'Interactive', description: 'Sounding off on local issues and taking a closer look at our community' },
    { logo: '/logos/hands-on.svg', title: 'Hands-On', description: 'Sounding off on local issues and taking a closer look at our community' },
    { logo: '/logos/social.svg', title: 'Social', description: 'Sounding off on local issues and taking a closer look at our community' },
]

const upcomingEvents = [
    {
        _id: '1',
        date: '2022-08-03T04:00:00.000Z',
        title: 'First Event with a much much longer title',
        description: 'short description about the event... like a single sentence'
    },
    {
        _id: '2',
        date: '2022-08-03T04:00:00.000Z',
        title: 'Second Event',
        description: 'short description about the event... like a single sentence'
    },
    {
        _id: '3',
        date: '2022-08-03T04:00:00.000Z',
        title: 'First Event',
        description: 'short description about the event... like a single sentence'
    },
    {
        _id: '4',
        date: '2022-08-03T04:00:00.000Z',
        title: 'First Event',
        description: 'short description about the event... like a single sentence'
    },
    {
        _id: '5',
        date: '2022-08-03T04:00:00.000Z',
        title: 'First Event',
        description: 'short description about the event... like a single sentence'
    },
    {
        _id: '6',
        date: '2022-08-03T04:00:00.000Z',
        title: 'First Event',
        description: 'short description about the event... like a single sentence'
    },
]

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>
        {/*  MISSION  */}
        <div className={styles.missionContainer}>
            <div
                className={styles.missionStatement}
            >
                Developing today&apos;s communities and tomorrow&apos;s leaders.
            </div>
            <div className={`sm md lg xl xxl ${styles.missionEvents}`}>
                <div>
                    <h1 style={{ textAlign: 'center', marginBottom: 30 }}>Our Next Event{upcomingEvents.length > 1 ? 's' : ''}</h1>
                    {
                        upcomingEvents.slice(0, 2).map(({ _id, date, title, description }) => <EventCard
                            key={_id}
                            date={date}
                            title={title}
                            description={description}
                        />)
                    }
                </div>
            </div>
        </div>

        {/*  WHAT WE DO  */}
        <LeftDashedBorder topOffset={115}>
            <h3 className={styles.whatWeDoHeader}>
                WHAT WE DO
            </h3>
            <div className={styles.whatWeDoContainer}>
                <div className={styles.whatWeDoMainContent}>
                    <div
                        className={styles.WhatWeDoSubtitle}
                    >
                        WE AIM FOR COMMUNITY SERVICE WITH A SOCIAL
                        <span> TWIST</span>.
                    </div>
                    <p>
                        What does that mean? It means members can participate in as many or as few volunteer opportunities as they’d like, and at the end of the day, they celebrate new friendships. In fact, our turnkey events only require one thing – for members to show up! Here’s a snapshot of Give Back Cincinnati’s impact:
                    </p>
                </div>
                <BulletList 
                    bullets={[
                        'More than 15,000 hours of service donated to-date',
                        '500+ houses painted throughout the region',
                        'The region\'s largest Thanksgiving meal',
                        'International service in Ghana, Romania, Peru, and beyond'
                    ]}
                    className={styles.whatWeDoList}
                />
            </div>
        </LeftDashedBorder>

        {/*  WHO WE ARE  */}
        <div
            className={styles.whoWeAreContainer}
        >
            {
                whoWeAreTexts.map((text, i) => (
                    <React.Fragment key={i}>
                        {
                            i === 3
                                ? <h2 className={styles.whoWeAreTitle}>
                                        WHO WE ARE
                                </h2>
                                : ''
                        }
                        <div className={styles.whoWeAreItem}>
                            {text}
                        </div>
                    </React.Fragment>
                ))
            }
        </div>


    {/*    Upcoming Events   */}
        <div
            className={styles.upcomingEventsContainer}
        >
            <h3 className={styles.upcomingEventsTitle} >
                Upcoming Events
            </h3>

            {
                upcomingEvents.map(({ _id, date, title, description }) => <EventCard
                    key={_id}
                    date={date}
                    title={title}
                    description={description}
                />)
            }
            <div className={styles.seeAllEvents}>
                <Button size='lg'>
                    See all Upcoming Events
                </Button>
            </div>
        </div>

    {/*    VOLUNTEER OPPORTUNITIES */}
        <div className={styles.volunteerOpportunitiesContainer}>
            <h3
            // fontFamily='stylized' fontSize={majorScale(4)} color='gbc-black'
            >
                Volunteer Opportunities
            </h3>
            <div className={styles.opportunityInnerContainer}>
                {
                    volunteerOpportunities.map(({ logo, title, description }) => (
                        <div className={styles.opportunity} key={title}>
                            <div
                                style={{ backgroundImage: `url(${logo})` } }
                            />
                            <h4>{title}</h4>
                            <p>
                                {description}
                            </p>
                        </div>
                    ))
                }
            </div>
        </div>

    </div>
  )
}

export default Home
