import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import {majorScale, Pane, Text} from 'evergreen-ui'
import { EventCard } from '../components/Events'
import { Button, BulletList } from '../components/Utils'

import styles from './index.module.scss'

const whoWeAreTexts = [
    <React.Fragment key={0}>A <span className='redUnderline'>Diverse</span> group of young professionals</React.Fragment>,
    <React.Fragment key={1}>COMMITTED TO <span className='redUnderline'>GIVING BACK</span> TO OUR COMMUNITY</React.Fragment>,
    <React.Fragment key={2}>CURRENT AND FUTURE <span className='redUnderline'>VISIONARY LEADERS</span></React.Fragment>,
    <React.Fragment key={3}>GLOBAL <span className='redUnderline'>ADVENTURERS</span> HELPING OUT ABROAD</React.Fragment>,
    <React.Fragment key={4}>DEDICATED TO <span className='redUnderline'>LOCAL</span> PHILANTHROPIC INITIATIVES</React.Fragment>,
]

const volunteerOpportunities = [
    { logo: '/logos/civic-engagement.svg', title: 'Civic Engagement', description: 'Sounding off on local issues and taking a closer look at our community' },
    { logo: '/logos/interactive.svg', title: 'Interactive', description: 'Sounding off on local issues and taking a closer look at our community' },
    { logo: '/logos/hands-on.svg', title: 'Hands-On', description: 'Sounding off on local issues and taking a closer look at our community' },
    { logo: '/logos/social.svg', title: 'Social', description: 'Sounding off on local issues and taking a closer look at our community' },
]

const upcomingEvents = [
    {
        _id: '1',
        date: '2022-08-03T04:00:00.000Z',
        title: 'First Event with a much much longer title',
        description: 'short description about the event... like a single sentence'
    },
    {
        _id: '2',
        date: '2022-08-03T04:00:00.000Z',
        title: 'Second Event',
        description: 'short description about the event... like a single sentence'
    },
    {
        _id: '3',
        date: '2022-08-03T04:00:00.000Z',
        title: 'First Event',
        description: 'short description about the event... like a single sentence'
    },
    {
        _id: '4',
        date: '2022-08-03T04:00:00.000Z',
        title: 'First Event',
        description: 'short description about the event... like a single sentence'
    },
    {
        _id: '5',
        date: '2022-08-03T04:00:00.000Z',
        title: 'First Event',
        description: 'short description about the event... like a single sentence'
    },
    {
        _id: '6',
        date: '2022-08-03T04:00:00.000Z',
        title: 'First Event',
        description: 'short description about the event... like a single sentence'
    },
]

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>
        {/*  MISSION  */}
        <div className={styles.missionContainer}>
            <div
                className={styles.missionStatement}
            >
                Developing today&apos;s communities and tomorrow&apos;s leaders.
            </div>
            <div className={`sm md lg xl xxl ${styles.missionEvents}`}>
                <div>
                    <h1 style={{ textAlign: 'center', marginBottom: 30 }}>Our Next Event{upcomingEvents.length > 1 ? 's' : ''}</h1>
                    {
                        upcomingEvents.slice(0, 2).map(({ _id, date, title, description }) => <EventCard
                            key={_id}
                            date={date}
                            title={title}
                            description={description}
                        />)
                    }
                </div>
            </div>
        </div>

        {/*  WHAT WE DO  */}
        <div
            className={styles.whatWeDoContainer}
        >
            <Pane
                borderLeft='1px dashed white'
                paddingTop={majorScale(4)}
            >
                <h3 className={styles.whatWeDo}>
                    WHAT WE DO
                </h3>

                <Pane
                    borderRadius='100px'
                    height='35px'
                    width='35px'
                    border='1px solid white'
                    display='inline-block'
                    position='relative'
                    left={-19}
                    top={30}
                    is='span'
                />
                <Pane className='what-we-do' textAlign='left' paddingLeft={majorScale(4)} display='flex' flexFlow='row-wrap' justifyContent='space-between'>
                    <Pane className='xs sm'>
                        <Text
                            color='white'
                            fontFamily='stylized'
                            textTransform='uppercase'
                            fontSize={majorScale(3)}
                            is='div'
                        >
                            WE AIM FOR COMMUNITY SERVICE WITH A SOCIAL
                            <Text
                                fontFamily='stylized'
                                textTransform='uppercase'
                                fontSize={majorScale(3)}
                                color='gbc-red'
                            > TWIST</Text>.
                        </Text>
                        <Pane marginTop={majorScale(2)}>
                            <Text
                                color='gray300'
                            >
                                What does that mean? It means members can participate in as many or as few volunteer opportunities as they’d like, and at the end of the day, they celebrate new friendships. In fact, our turnkey events only require one thing – for members to show up! Here’s a snapshot of Give Back Cincinnati’s impact:
                            </Text>
                        </Pane>
                    </Pane>
                    <Pane className='md lg xl xxl' width='45%' maxWidth={400}>
                        <Text
                            color='white'
                            fontFamily='stylized'
                            textTransform='uppercase'
                            fontSize={majorScale(3)}
                            is='div'
                        >
                            WE AIM FOR COMMUNITY SERVICE WITH A SOCIAL
                            <Text
                                fontFamily='stylized'
                                textTransform='uppercase'
                                fontSize={majorScale(3)}
                                color='gbc-red'
                            > TWIST</Text>.
                        </Text>
                        <Pane marginTop={majorScale(2)}>
                            <Text
                                color='gray300'
                            >
                                What does that mean? It means members can participate in as many or as few volunteer opportunities as they’d like, and at the end of the day, they celebrate new friendships. In fact, our turnkey events only require one thing – for members to show up! Here’s a snapshot of Give Back Cincinnati’s impact:
                            </Text>
                        </Pane>
                    </Pane>

                    <BulletList 
                        bullets={[
                            'More than 15,000 hours of service donated to-date',
                            '500+ houses painted throughout the region',
                            'The region\'s largest Thanksgiving meal',
                            'International service in Ghana, Romania, Peru, and beyond'
                        ]}
                    />
                </Pane>
            </Pane>
        </div>

        {/*  WHO WE ARE  */}
        <Pane
            minHeight='300px'
            display='flex'
            flexFlow='row wrap'
            justifyContent='space-around'
        >
            {
                whoWeAreTexts.map((text, i) => (
                    <React.Fragment key={i}>
                        {
                            i === 3
                                ? <Pane width='100%' textAlign='center' marginY={majorScale(5)}>
                                    <Text
                                        color='gbc-red'
                                        fontSize={majorScale(9)}
                                        fontFamily='stylized'
                                    >
                                        WHO WE ARE
                                    </Text>
                                </Pane>
                                : ''
                        }
                        <Pane width='100%' margin={majorScale(2)} lineHeight={2} className='xs sm' textAlign='center'>
                            <Text
                                textTransform='uppercase'
                                color='gbc-black'
                                fontFamily='stylized'
                                fontSize={majorScale(3)}
                            >
                                {text}
                            </Text>
                        </Pane>
                        <Pane width='33%' maxWidth={250} padding={majorScale(2)} lineHeight={2} className='md lg xl xxl'>
                            <Text
                                textTransform='uppercase'
                                color='gbc-black'
                                fontFamily='stylized'
                                fontSize={majorScale(3)}
                            >
                                {text}
                            </Text>
                        </Pane>
                    </React.Fragment>
                ))
            }
        </Pane>


    {/*    Upcoming Events   */}
        <Pane
            background={'gray300'}
            display='flex'
            flexFlow='row wrap'
            justifyContent='space-around'
            padding={majorScale(5)}
        >
            <Pane width='100%' textAlign='center' paddingBottom={majorScale(3)}>
                <Text fontFamily='stylized' fontSize={majorScale(5)} color='gbc-black'>
                    Upcoming Events
                </Text>
            </Pane>

            {
                upcomingEvents.map(({ _id, date, title, description }) => <EventCard
                    key={_id}
                    date={date}
                    title={title}
                    description={description}
                />)
            }

            <Pane width='100%' margin='auto' textAlign='center' paddingTop={majorScale(2)}>
                <Button size='lg'>
                    See all Upcoming Events
                </Button>
            </Pane>
        </Pane>

    {/*    VOLUNTEER OPPORTUNITIES */}
        <Pane
            minHeight='300px'
            backgroundColor='white'
        >
            <Pane
                textAlign={'center'}
                paddingTop={majorScale(4)}
            >
                <Text fontFamily='stylized' fontSize={majorScale(4)} color='gbc-black'>
                    Volunteer Opportunities
                </Text>
            </Pane>
            <Pane display='flex' flexFlow='row wrap' justifyContent='space-around'>
                {
                    volunteerOpportunities.map(({ logo, title, description }) => (
                        <Pane key={title} textAlign='center' paddingBottom={majorScale(5)} maxWidth={250}>
                            <Pane
                                display='block'
                                minHeight={180}
                                maxWidth={120}
                                marginTop={majorScale(4)}
                                marginX='auto'
                                backgroundImage={`url(${logo})`}
                                backgroundRepeat='no-repeat'
                                backgroundSize='contain'
                                backgroundPosition='bottom'
                            />
                            <Text
                                color='gbc-red'
                                fontFamily='stylized'
                                fontSize={majorScale(3)}
                                display='block'
                            >{title}</Text>
                            <Pane paddingTop={majorScale(3)}>
                                <Text display='block'>
                                    {description}
                                </Text>
                            </Pane>
                        </Pane>
                    ))
                }
            </Pane>
        </Pane>

    </div>
  )
}

export default Home
