import type { NextPage } from 'next'
import Head from 'next/head'
import { Button, Text, Pane } from 'evergreen-ui'

const Home: NextPage = () => {
  return (
    <Pane>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div>
        <Button appearance='gbc-red'>Click Me</Button>
        <Text>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </Text>
      </div>
    </Pane>
  )
}

export default Home
