import type { NextPage } from 'next'
import Head from 'next/head'
import {majorScale, minorScale, Pane, Text} from 'evergreen-ui'

const highlightTextStyles = {
    color: 'white',
    fontFamily: 'stylized',
    textTransform: 'uppercase',
    fontSize: majorScale(3)
}

const volunteerOpportunities = [
    { logo: '/logos/civic-engagement.svg', title: 'Civic Engagement', description: 'Sounding off on local issues and taking a closer look at our community' },
    { logo: '/logos/interactive.svg', title: 'Interactive', description: 'Sounding off on local issues and taking a closer look at our community' },
    { logo: '/logos/hands-on.svg', title: 'Hands-On', description: 'Sounding off on local issues and taking a closer look at our community' },
    { logo: '/logos/social.svg', title: 'Social', description: 'Sounding off on local issues and taking a closer look at our community' },
]

const Home: NextPage = () => {
  return (
    <Pane>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>
        {/*  MISSION  */}
        <Pane
            background='gbc-red'
            backgroundImage='url(/city-skyline-red.svg)'
            backgroundRepeat='no-repeat'
            backgroundSize='contain'
            backgroundPosition='bottom'
            minHeight='300px'
            textAlign='center'
            padding={majorScale(3)}
        >
            <Text
                color='white'
                fontSize={majorScale(3)}
                fontFamily='stylized'
            >
                Developing today’s communities and tomorrow’s leaders.
            </Text>
        </Pane>

        {/*  WHAT WE DO  */}
        <Pane
            background='gbc-black'
            paddingX={majorScale(5)}
        >
            <Pane
                borderLeft='1px dashed white'
                paddingY={majorScale(3)}
                minHeight='300px'
            >
                <Pane
                    textAlign={'center'}
                >
                    <Text fontFamily='stylized' fontSize={majorScale(4)} color='white'>
                        WHAT WE DO
                    </Text>
                </Pane>

                <Pane
                    borderRadius='100px'
                    height='35px'
                    width='35px'
                    border='1px solid white'
                    display='inline-block'
                    position='relative'
                    left={-19}
                    top={30}
                    is='span'
                />
                <Pane textAlign='left' paddingLeft={majorScale(4)}>
                    <Text
                        color='white'
                        fontFamily='stylized'
                        textTransform='uppercase'
                        fontSize={majorScale(3)}
                        is='div'
                    >
                        WE AIM FOR COMMUNITY SERVICE WITH A SOCIAL
                        <Text
                            fontFamily='stylized'
                            textTransform='uppercase'
                            fontSize={majorScale(3)}
                            color='gbc-red'
                        > TWIST</Text>.
                    </Text>
                    <Pane marginTop={majorScale(2)}>
                        <Text
                            color='gray300'
                        >
                            What does that mean? It means members can participate in as many or as few volunteer opportunities as they’d like, and at the end of the day, they celebrate new friendships. In fact, our turnkey events only require one thing – for members to show up! Here’s a snapshot of Give Back Cincinnati’s impact:
                        </Text>
                    </Pane>
                    <Pane marginTop={majorScale(3)}>
                        {
                            [
                                'More than 15,000 hours of service donated to-date',
                                '500+ houses painted throughout the region',
                                'The region\'s largest Thanksgiving meal',
                                'International service in Ghana, Romania, Peru, and beyond'
                            ].map(bulletPoint => <Text key={bulletPoint} className='bulletPoint' color='white'>{bulletPoint}</Text>)
                        }
                    </Pane>
                </Pane>
            </Pane>
        </Pane>

        {/*  WHO WE ARE  */}
        <Pane
            minHeight='300px'
            display='flex'
            flexFlow='row wrap'
            justifyContent='space-around'
        >
            <Pane width='100%' margin={majorScale(2)} lineHeight={2}>
                <Text
                    textTransform='uppercase'
                    color='gbc-black'
                    fontFamily='stylized'
                    fontSize={majorScale(3)}
                >
                    A <span className='redUnderline'>Diverse</span> group of young professionals
                </Text>
            </Pane>
            <Pane width='100%' margin={majorScale(2)}>
                <Text
                    textTransform='uppercase'
                    color='gbc-black'
                    fontFamily='stylized'
                    fontSize={majorScale(3)}
                >
                    COMMITTED TO <span className='redUnderline'>GIVING BACK</span> TO OUR COMMUNITY
                </Text>
            </Pane>
            <Pane width='100%' margin={majorScale(2)} lineHeight={2}>
                <Text
                    textTransform='uppercase'
                    color='gbc-black'
                    fontFamily='stylized'
                    fontSize={majorScale(3)}
                >
                    CURRENT AND FUTURE <span className='redUnderline'>VISIONARY LEADERS</span>
                </Text>
            </Pane>
            <Pane width='100%' textAlign='center' marginY={majorScale(5)}>
                <Text
                    color='gbc-red'
                    fontSize={majorScale(9)}
                    fontFamily='stylized'
                >
                    WHO WE ARE
                </Text>
            </Pane>
            <Pane width='100%' margin={majorScale(2)} lineHeight={2}>
                <Text
                    textTransform='uppercase'
                    color='gbc-black'
                    fontFamily='stylized'
                    fontSize={majorScale(3)}
                >
                    GLOBAL <span className='redUnderline'>ADVENTURERS</span> HELPING OUT ABROAD
                </Text>
            </Pane>
            <Pane width='100%' margin={majorScale(2)} lineHeight={2}>
                <Text
                    textTransform='uppercase'
                    color='gbc-black'
                    fontFamily='stylized'
                    fontSize={majorScale(3)}
                >
                    DEDICATED TO <span className='redUnderline'>LOCAL</span> PHILANTHROPIC INITIATIVES
                </Text>
            </Pane>
            <Pane width='110px' />
        </Pane>

    {/*    Upcoming Events   */}
        <Pane
            minHeight='300px'
            background={'gray300'}
        >
            <Text>WIP: Upcoming Events</Text>
        </Pane>

    {/*    VOLUNTEER OPPORTUNITIES */}
        <Pane
            minHeight='300px'
            backgroundColor='white'
        >
            <Pane
                textAlign={'center'}
                paddingTop={majorScale(4)}
            >
                <Text fontFamily='stylized' fontSize={majorScale(4)} color='gbc-black'>
                    Volunteer Opportunities
                </Text>
            </Pane>
            <Pane display='flex' flexFlow='row wrap' justifyContent='space-around'>
                {
                    volunteerOpportunities.map(({ logo, title, description }) => (
                        <Pane key={title} textAlign='center' paddingBottom={majorScale(5)} maxWidth={250}>
                            <Pane
                                display='block'
                                minHeight={180}
                                maxWidth={120}
                                marginTop={majorScale(4)}
                                marginX='auto'
                                backgroundImage={`url(${logo})`}
                                backgroundRepeat='no-repeat'
                                backgroundSize='contain'
                                backgroundPosition='bottom'
                            />
                            <Text
                                color='gbc-red'
                                fontFamily='stylized'
                                fontSize={majorScale(3)}
                                display='block'
                            >{title}</Text>
                            <Pane paddingTop={majorScale(3)}>
                                <Text display='block'>
                                    {description}
                                </Text>
                            </Pane>
                        </Pane>
                    ))
                }
            </Pane>
        </Pane>

    </Pane>
  )
}

export default Home
