import type { NextPage } from 'next'
import Head from 'next/head'
import {majorScale, Pane, Text} from 'evergreen-ui'

const highlightTextStyles = {
    color: 'white',
    fontFamily: 'stylized',
    textTransform: 'uppercase',
    fontSize: majorScale(3)
}

const Home: NextPage = () => {
  return (
    <Pane>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>

        <Pane
            background='gbc-red'
            backgroundImage='url(/city-skyline-red.svg)'
            backgroundRepeat='no-repeat'
            backgroundSize='contain'
            backgroundPosition='bottom'
            minHeight='300px'
            textAlign='center'
            padding={majorScale(3)}
        >
            <Text
                color='white'
                fontSize={majorScale(3)}
                fontFamily='stylized'
            >
                Developing today’s communities and tomorrow’s leaders.
            </Text>
        </Pane>
        <Pane
            background='gbc-black'
            paddingX={majorScale(5)}
        >
            <Pane
                borderLeft='1px dashed white'
                paddingTop={majorScale(3)}
                minHeight='300px'
            >
                <Pane
                    textAlign={'center'}
                >
                    <Text fontFamily='stylized' fontSize={majorScale(4)} color='white'>
                        WHAT WE DO
                    </Text>
                </Pane>

                <Pane
                    borderRadius='100px'
                    height='35px'
                    width='35px'
                    border='1px solid white'
                    display='inline-block'
                    position='relative'
                    left={-19}
                    top={30}
                    is='span'
                />
                <Pane textAlign='left' paddingLeft={majorScale(4)}>
                    <Text
                        color='white'
                        fontFamily='stylized'
                        textTransform='uppercase'
                        fontSize={majorScale(3)}
                        is='div'
                    >
                        WE AIM FOR COMMUNITY SERVICE WITH A SOCIAL
                        <Text
                            fontFamily='stylized'
                            textTransform='uppercase'
                            fontSize={majorScale(3)}
                            color='gbc-red'
                        > TWIST</Text>.
                    </Text>
                    <Pane marginTop={majorScale(2)}>
                        <Text
                            color='gray300'
                        >
                            What does that mean? It means members can participate in as many or as few volunteer opportunities as they’d like, and at the end of the day, they celebrate new friendships. In fact, our turnkey events only require one thing – for members to show up! Here’s a snapshot of Give Back Cincinnati’s impact:
                        </Text>
                    </Pane>
                </Pane>
            </Pane>
        </Pane>
    </Pane>
  )
}

export default Home
